### PR TITLE
fix: add locations to explain requests

### LINKED ISSUE #2049: Pinned files should be refreshed when they change
When I Pin a file and then change that file, my changes are not picked up by Navie. The file is Pinned with the original file content, and doesn't seem to be refreshed when I edit the file.

### PR DESCRIPTION
**Pull request by apotterri**
Add the locations of pinned files to Navie requests, rather than their contents.

Fixes #2049 .

### CODE REVIEW

File: packages/navie/src/navie.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ export interface ClientRequest {
   question: string;
   codeSelection?: string;
```
Comment (kgilpin) [inline packages/navie/src/navie.ts:47]: Historically, this `codeSelection` was the code that the user had selected in their IDE when they opened Navie. So, it was a string. And even then, as a string, it was deficient, because it didn't include the location from which the selected code was obtained.

So, I think there is an opportunity to redefine this codeSelection argument as a `string | UserContext` type, where `UserContext` can support all the different strategies that the user might employ to send context to Navie. 

This would include, but not necessarily be limited to:

- Code selections. A code selection is a range (start..end) from a file, plus the specific code from that range.
- Files. A file is just a file location. Navie should use the context API to retrieve the contents of that file. This operation is already supported in the context lookup facility. 

```
    type ContextV1.ContextRequest = {
        tokenCount: number;
        vectorTerms: string[]; <-- Leave this blank to fetch locations instead.
    };
    type ContextFilters = {
        recent?: boolean;
        locations?: string[]; <-- Can be populated to fetch the full contents of specified files.
        itemTypes?: ContextItemType[];
        labels?: ContextLabel[];
        exclude?: string[];
        include?: string[];
    };
    type ContextRequest = ContextV1.ContextRequest & ContextFilters;
```

Comment (apotterri) [reply packages/navie/src/navie.ts:47]: > Lookup by location is already supported like this:

Yes, I saw this, and a ContextRequest is ultimately the way file contents get retrieved. As far as I can tell, though, the existing interface for an Explain request doesn't allow the client to pass a ContextRequest. Instead, the pieces of the ContextRequest are passed as function parameters, and then get assembled into filters here: https://github.com/getappmap/appmap-js/blob/main/packages/navie/src/services/context-service.ts#L39 .

Comment (kgilpin) [reply packages/navie/src/navie.ts:47]: You can check out the generate agent to see how it fetches full file contents

Comment (apotterri) [reply packages/navie/src/navie.ts:47]: I guess I'm confused by this comment. The Explain agent uses the `searchContext` method of `ContextService`, which has this signature:
```
  async searchContext(
    options: AgentOptions,
    tokensAvailable: () => number,
    additionalTerms: string[] = [],
    locations?: string[]
  ): Promise<void> 
```
This sets the passed `locations` on a `ContextFilter`, which it then passes to `this.lookupContextService.lookupContext`.

The Generate agent uses `ContextService.locationContext`, which has this signature:
```
  async locationContext(fileNames: string[]): Promise<void>
```
`locationContext` sets `fileNames` as the `locations` on a `ContextFilter`, then it too calls `this.lookupContextService.lookupContext`.

Aren't these doing the same thing to fetch the full file contents? I understood your suggestion about creating `UserContextItem` to encapsulate all the different kinds of context a user can provide, and then passing an array of those, rather than having `codeSelection` and `locations` be separate arguments. Can't this array then be passed to `searchContext` as part of `AgentOptions`?

**Comment by apotterri** [comment]
Changing `ClientRequest` seems like it necessitates changes on both sides of the RPC boundary, i.e. for both clients that make RPC calls, as well as for the server-side functions that handle the calls.

[89c769e](https://github.com/getappmap/appmap-js/pull/2050/commits/89c769eafae0a147d3cfa8a3356af52e70ca35b6) attempts to address the interface changes necessary.

File: packages/cli/src/rpc/explain/explain.ts [hunk 2]
```diff
@@ -208,15 +213,35 @@ export class Explain extends EventEmitter {
...
+      let ret = v.type.length;
+      switch (v.type) {
+        case ContextV2.ContextItemType.CodeSelection:
+          ret += v.location!.length + v.content!.length;
+          break;
+        case ContextV2.ContextItemType.CodeSnippet:
+          ret += v.content!.length;
+          break;
+        case ContextV2.ContextItemType.File:
+          ret += v.location!.length;
```
Comment (dustinbyrne) [inline packages/cli/src/rpc/explain/explain.ts:232]: We shouldn't need to use the non-null assertion operator, it generally indicates something is mis-typed.

Consider something like:
```ts
interface CodeSelectionContextItem {
    type: 'code-selection';
    location: string;
    content: string;
}

interface CodeSnippetContextItem {
    type: 'code-snippet';
    content: string;
    location?: never;
}

// This doesn't include the full list
type UserContextItem = CodeSelectionContextItem | CodeSnippetContextItem;
```

**Review by kgilpin — COMMENTED** [review]
This seems directionally good.

File: packages/navie/src/user-context.ts [hunk 3]
```diff
@@ -0,0 +1,69 @@
+export namespace UserContext {
+  export type CodeSelectionItem = {
+    type: 'code-selection';
+    location: string;
```
Comment (kgilpin) [inline packages/navie/src/user-context.ts:4]: Since we know this is based on a file, that file can be a candidate for code generation output.

File: packages/navie/src/user-context.ts [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    content: string;
+  };
+
+  export type CodeSnippetItem = {
+    type: 'code-snippet';
```
Comment (kgilpin) [inline packages/navie/src/user-context.ts:9]: These do not have an associated location; which actually might not be correct. If the user is Pinning a generated snippet, might that snippet have an associated location?

File: packages/navie/src/user-context.ts [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    const pinnedItems = items.filter(
+      (i) => UserContext.isCodeSelectionItem(i) || UserContext.isFileItem(i)
+    );
+    const snippets = items.filter((i) => UserContext.isCodeSnippetItem(i));
+    if (pinnedItems.length > 0 || snippets.length > 0) {
+      renderedItems.push('<user-provided-context>');
+      if (pinnedItems.length > 0) {
+        renderedItems.push(
+          `<!-- Pinned items are snippets that I have saved from earlier in the conversation -->`,
+          ...pinnedItems.map((i) => `<pinned-context>\n${renderItem(i)}\n</pinned-context>`)
```
Comment (kgilpin) [inline packages/navie/src/user-context.ts:56]: And as discussed above, these may also have a location.

File: packages/navie/src/agent.ts [hunk 6]
```diff
@@ -32,6 +33,11 @@ export class AgentOptions {
   buildContextFilters(): ContextV2.ContextFilters {
     const filters: ContextV2.ContextFilters = {};
     if (this.contextLabels) filters.labels = this.contextLabels;
+    if (this.codeSelection && typeof this.codeSelection !== 'string') {
+      filters.locations = this.codeSelection
+        .filter(UserContext.isFileItem)
```
Comment (kgilpin) [inline packages/navie/src/agent.ts:38]: May want to change this to a filter like `hasLocation`

**Comment by apotterri** [comment]
@kgilpin I believe the changes in the `!fixup` commits address the concerns you raised.

One outstanding issue: how should pinned files be handled when Navie is remote? https://github.com/getappmap/appmap-js/blob/explain-locations_20241007/packages/cli/src/rpc/explain/navie/navie-remote.ts#L190

File: packages/components/src/components/chat/MarkdownCodeSnippet.vue [hunk 7]
```diff
@@ -96,6 +96,11 @@ export default Vue.extend({
     },
     decodedLocation(): string | undefined {
       // The location may be URI encoded to avoid issues with special characters.
+      console.log(
+        `decodedLocation, this.location: ${
+          this.location
+        } decodeURIComponent(this.location): ${decodeURIComponent(this.location)}`
+      );
```
Comment (dustinbyrne) [inline packages/components/src/components/chat/MarkdownCodeSnippet.vue:103]: This looks like it can be dropped

File: packages/navie/src/user-context.ts [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+    const renderItem = (i: UserContext.ContextItem) => {
+      if (UserContext.isCodeSelectionItem(i) && includeContent) {
+        return `<code-selection>\n${i.content}\n</code-selection>`;
+      } else if (UserContext.isCodeSnippetItem(i)) {
+        const content = includeContent ? `\n<content>${i.content}</content>\n'` : '';
+        return `<pinned-snippet>
+  <location>${i.location}</location>${content}
+</pinned-snippet>`;
+      } else if (UserContext.isFileItem(i)) {
+        return `<pinned-file><location>${i.location}</location></pinned-file>`;
```
Comment (dustinbyrne) [inline packages/navie/src/user-context.ts:48]: Pinned files never include content?

File: packages/components/src/components/chat/MarkdownCodeSnippet.vue (hunk 7 above)
Comment (apotterri) [reply packages/components/src/components/chat/MarkdownCodeSnippet.vue]: Thanks, fixed.

File: packages/navie/src/user-context.ts (hunk 8 above)
Comment (apotterri) [reply packages/navie/src/user-context.ts:48]: That's right, pinned files never include content. #2049 is about stale file contents. These changes avoid that by having context selection always read the file.

Comment (apotterri) [reply packages/navie/src/user-context.ts:48]: One of the significant changes here is this: https://github.com/getappmap/appmap-js/blob/explain-locations_20241007/packages/navie/src/agent.ts#L36 . When a `ContextItem` has a `location`, it's included in the `ContextFilters`. As I understand it, this is the same mechanism that `@generate` uses to read the full contents of files.

You can see this in action in Navie's log:
```
[context-service] Searching for context
Tokens (prompt/compl/total): 657/26/683, cost: $0.00
Vector terms response:
Context: Exception handling in Java
Instructions: Explain how exception handling is managed
---
Terms: exception handling +Java try catch finally
Explain received context request: search
Collecting context with parameters: sourceDirectories: /Users/ajp/src/apotterri/ejb-example, charLimit: 16503, appmapDirectories: /Users/ajp/src/apotterri/ejb-example, keywords: exception, handling, java, try, catch, finally, locations: /Users/ajp/src/apotterri/ejb-example/src/main/java/org/superbiz/remote/App.java
Parsed locations: /Users/ajp/src/apotterri/ejb-example/src/main/java/org/superbiz/remote/App.java
[location-context] Candidate locations: /Users/ajp/src/apotterri/ejb-example/src/main/java/org/superbiz/remote/App.java
[location-context] Extracting snippet for location: /Users/ajp/src/apotterri/ejb-example/src/main/java/org/superbiz/remote/App.java (2127 bytes)
```

What you see under Code Snippets is in addition to the contents of files. This redundancy is what this issue is about: https://github.com/getappmap/appmap-js/issues/1984 .

**Review by dustinbyrne — APPROVED** [review]
