### PR TITLE
fix: show pinning help

### LINKED ISSUE #1988: Context area explains the operation of "Pinned" content
When there is no Pinned content, the Context area should explain the concept of Pinned content and how to add pinned content.

1) Use the Pin button from a Navie answer
2) Drag and drop a file (Using Shift)
3) Use the command "AppMap: Add to Context"

### LINKED ISSUE #2011: When switching to Navie webview, the input area should get focus
The input area doesn't get focus. So, it's necessary to move the mouse over to the input area and click it before typing anything.

When switching between Navie webview and code, it's cumbersome to have to do so.

--

* Implement in the components package

### PR DESCRIPTION
**Pull request by apotterri**
Show help text when there are no pinned items in the Context.

Fixes #1988 .
Fixes #2011 .

### CODE REVIEW

**Comment by kgilpin** [comment]
Calling the entire area "Navie's Context Sources" and then calling a subsection of that area "Navie's Context" is confusing.

Screen Shot 2024-10-02 at 9 43 30 AM

Remove the major heading "Navie's Context Sources".

**Comment by kgilpin** [comment]
The (info) pin disappears when the search context arrives:

Screen Shot 2024-10-02 at 9 47 03 AM

File: packages/components/src/components/chat-search/IntelliJNotice.vue [hunk 1]
```diff
@@ -0,0 +1,46 @@
+<template>
+  <div>
+    <button @click.prevent="addFiles">&#xFF0B; add files</button>
```
Comment (dustinbyrne) [inline packages/components/src/components/chat-search/IntelliJNotice.vue:3]: This should be an SVG, otherwise we have no control over how this character is rendered
image

Comment (dustinbyrne) [reply packages/components/src/components/chat-search/IntelliJNotice.vue:3]: Also, we can't have unstyled buttons. At least use the `v-button` component.

File: packages/components/src/components/chat/ChatInput.vue [hunk 2]
```diff
@@ -116,6 +121,14 @@ export default {
     isSelectingCommand() {
       return this.$refs.autocomplete.isVisible;
     },
+    inputClass() {
+      return {
+        // See the comment in getappmap/vscode-appland/web/src/app.js for why `focus` is applied to
+        // the input
+        focus: true,
```
Comment (dustinbyrne) [inline packages/components/src/components/chat/ChatInput.vue:128]: If we truly have to do this, use a data attribute and not an empty class

File: packages/components/src/components/AddFileButton.vue [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  </v-button>
+</template>
+
+<script lang="ts">
+//@ts-nocheck
+import PlusIcon from '../assets/plus.svg';
+export default {
+  name: 'v-chat-search',
+  components: {
+    PlusIcon,
```
Comment (dustinbyrne) [inline packages/components/src/components/AddFileButton.vue:13]: `v-button` is not registered so the button does not render

Comment (dustinbyrne) [reply packages/components/src/components/AddFileButton.vue:13]: image

File: packages/components/src/components/AddFileButton.vue [hunk 4]
```diff
@@ -0,0 +1,27 @@
+<template>
+  <v-button class="clear add-file__button" size="small" kind="ghost">
```
Comment (dustinbyrne) [inline packages/components/src/components/AddFileButton.vue:2]: `clear` is not a class

File: packages/components/src/components/chat-search/Context.vue [hunk 5]
```diff
@@ -1,9 +1,8 @@
 <template>
   <div class="context" data-cy="context">
-    <template v-if="!contextResponse && !hasPinnedItems">
+    <template v-if="!contextResponse">
       <div class="context__notice-container">
```
Comment (dustinbyrne) [inline packages/components/src/components/chat-search/Context.vue:4]: The bottom area of the context notice is clipped
image

File: packages/components/src/pages/ChatSearch.vue [hunk 6]
```diff
@@ -655,6 +789,27 @@ $border-color: darken($gray4, 10%);
...
+      display: flex;
+      flex-direction: column;
+      overflow-y: auto;
+      margin-bottom: 0;
+    }
+
+    .pinned-items-wrapper .search-container {
+      max-height: 33vh;
+      border-bottom: 1px dashed $white;
+    }
```
Comment (dustinbyrne) [inline packages/components/src/pages/ChatSearch.vue:810]: This border does not lay on the bottom margins of the 'pinned items' container, so it makes the 'selected by Navie' header appear have a lot of a lot of margin on top.
image

image

File: packages/components/src/pages/ChatSearch.vue [hunk 7]
```diff
@@ -39,38 +40,89 @@
...
+      <div class="context-wrapper">
+        <h2>Selected by Navie</h2>
+        <div class="search-container">
+          <v-context
+            class="no-match-instructions"
+            :appmap-stats="appmapStats"
+            :context-response="contextResponse"
+          />
+        </div>
+      </div>
```
Comment (dustinbyrne) [inline packages/components/src/pages/ChatSearch.vue:93]: These aren't scrolling the correct area. The scroll bars should span the entire height of the container. The container should also not scroll unless the content is overflowing.
image

File: packages/components/src/pages/ChatSearch.vue [hunk 8]
```diff
@@ -655,6 +789,27 @@ $border-color: darken($gray4, 10%);
...
+    .context-wrapper {
+      display: flex;
+      flex-direction: column;
+      overflow-y: auto;
+      margin-bottom: 0;
+    }
+
+    .pinned-items-wrapper .search-container {
+      max-height: 33vh;
+      border-bottom: 1px dashed $white;
```
Comment (dustinbyrne) [inline packages/components/src/pages/ChatSearch.vue:809]: `$white` is too bright here - try something like `rgba($white, 0.33)`

File: packages/components/src/pages/ChatSearch.vue (hunk 7 above)
Comment (dustinbyrne) [reply packages/components/src/pages/ChatSearch.vue:93]: Notice the placement and sizing of the scrollbars in these two images. The container would ideally take up its maximum height even before filling up with context items.

image

image

Comment (apotterri) [reply packages/components/src/pages/ChatSearch.vue:93]: Yeah, that's the problem I fixed. I thought you were saying there was an additional problem, but maybe not?

Comment (dustinbyrne) [reply packages/components/src/pages/ChatSearch.vue:93]: It looks better now

File: packages/components/src/pages/ChatSearch.vue [hunk 9]
```diff
@@ -423,9 +493,7 @@ export default {
         this.ask.on('stop', onStop);
 
         const explainRequest = {
-          question: message
-            .replace(/^@generate/, '@generate /format=xml')
-            .replace(/^@test/, '@test /format=xml'),
```
Comment (dustinbyrne) [inline packages/components/src/pages/ChatSearch.vue:428]: Rebase issue here? I think `@test /format=xml` should be kept.

**Comment by apotterri** [comment]
Yeah, that definitely wasn't a change I intended. I'll make sure not to
merge it.

File: packages/components/src/pages/ChatSearch.vue (hunk 9 above)
Comment (apotterri) [reply packages/components/src/pages/ChatSearch.vue]: I went back over my reflog and found where this change was introduced. It doesn't appear to have been part of a rebase, though the subject of the commit message is a little weird: it's labeled `!fixup !fixup`. I try to make a point of never fixing up a `!fixup` commit, so I'm not entirely sure how this happened. I think I missed it because it sort of looked like a formatting change, and I didn't notice that it was actually a behavior change.

In any event, this was the only unintentional change introduced in the `!fixup !fixup` commit. I also went back over all the changes in the PR, and didn't see anything else that looked out of place.

LMK if you have any other concerns I can address. Otherwise, I think this is ready to go.

**Review by dustinbyrne — APPROVED** [review]
