### PR TITLE
fix: fix broken tests

### LINKED ISSUE #765: Fix broken tests for CLI

### PR DESCRIPTION
**Pull request by ahtrotta**
Fixes #765

### CODE REVIEW

File: packages/cli/src/cmds/runCommand.ts [hunk 1]
```diff
@@ -28,7 +28,11 @@ export default async function runCommand(
       name: `${commandPrefix}:exit-ok`,
     });
 
-    flushTelemetry(0);
+    // only run this when not in Travis builds becuase
+    // this immediately exits the test suite in Travis
+    if (!process.env.TRAVIS) {
+      flushTelemetry(0);
```
Comment (dividedmind) [inline packages/cli/src/cmds/runCommand.ts:34]: I think flushTelemetry call (and function) should just be removed. This was needed because cli used to do `process.exit()` which killed the process before the telemetry had the chance to be flushed — this is discouraged in node precisely because it prevents any scheduled actions to run.

I believe I had changed all the places where that was done to set `process.exitStatus =` instead, which is the recommended way to set the exit status and avoids this problem. Therefore this is just not needed anymore.

File: packages/cli/tests/unit/depends.spec.ts [hunk 2]
```diff
@@ -1,10 +1,11 @@
...
-const Fingerprinter = require('../../src/fingerprint/fingerprinter');
-const { listAppMapFiles, verbose } = require('../../src/utils');
+import { utimesSync } from 'fs';
+import { join } from 'path';
+import tmp from 'tmp';
+import fs from 'fs-extra';
+
+import Fingerprinter from '../../src/fingerprint/fingerprinter';
+import Depends from '../../src/depends';
+import { listAppMapFiles, verbose } from '../../src/utils';
```
Comment (dividedmind) [inline packages/cli/tests/unit/depends.spec.ts:8]: Please separate style commits from substantial ones. It makes it unnecessarily difficult to review the PR and use `git blame` later.

**Review by dividedmind — CHANGES_REQUESTED** [review]

**Review by dividedmind — APPROVED** [review]
This `exitCode` changes are perfect, thanks!

I'd still like you to separate the style changes in a separate commit. 

BTW, those fixup commits are a bit unorthodox. They don't seem to have been generated with `git commit --fixup`, so it's difficult to say what they should fix up (generally, here there's only one commit, I suppose :) ) and they don't get automatically applied by `git rebase --interactive`.

But that's fine as long as you clean this up before merging :) Thanks!

**Comment by ahtrotta** [comment]
Great! 

Sorry that I didn't split up the commits, I thought you meant it as a thing to do in the future. I'll split it up before I merge it.

The fixup commits were just done manually by starting the commit message with `fixup!`. I usually squash my commits down to one or two commits before merging, so I just wrote the fixup commits like that as a notice to myself for which commits to squash. I'll be sure to use `git commit --fixup` in the future, though!

**Comment by dividedmind** [comment]
> Great!
> 
> Sorry that I didn't split up the commits, I thought you meant it as a thing to do in the future. I'll split it up before I merge it.
> 
> The fixup commits were just done manually by starting the commit message with `fixup!`. I usually squash my commits down to one or two commits before merging, so I just wrote the fixup commits like that as a notice to myself for which commits to squash. I'll be sure to use `git commit --fixup` in the future, though!

Sure, makes sense! Just thought maybe you don't know about the `--fixup` and how it works together with `rebase --interactive`.

BTW, this should be good to go as soon as we merge #767 and this is rebased on top of that.
