### PR TITLE
fix: Only "tests" AppMaps can be new or changed

### LINKED ISSUE #1274: Only "test" AppMaps should be considered "new" in the "compare" report

### PR DESCRIPTION
**Pull request by kgilpin**
Only report "tests"-recorded AppMaps as new or changed.

If there are other types of AppMaps, such as requests recordings, in the AppMap archive, don't consider these when reporting new & changed AppMaps, because they don't have stable names.

Fixes #1274

### CODE REVIEW

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 1]
```diff
@@ -1,15 +1,15 @@
...
 import { FormatType, format } from '@appland/sequence-diagram';
 import { queue } from 'async';
 import assert from 'assert';
 
 import { DiffDiagrams } from '../../sequenceDiagramDiff/DiffDiagrams';
 import { ArchiveMetadata } from '../archive/ArchiveMetadata';
-import { AppMapData } from './AppMapData';
-import { AppMapIndex } from './AppMapIndex';
+import { Paths } from './Paths';
+import { Digests } from './Digests';
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:12]: I've chosen better names here, that's all. The name change is isolated to one commit.

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 2]
```diff
@@ -155,30 +148,73 @@ export default class ChangeReporter {
...
+    assert(appMapMetadata);
+    assert(baseAppMaps);
+    assert(headAppMaps);
+    assert(failedAppMaps);
+
+    const generator = new ReportFieldCalculator(this);
+    const apiDiff = await generator.apiDiff(options.reportRemoved);
+
+    const isNewFn = isNew(baseAppMaps, isTest(appMapMetadata));
+    const isChangedFn = isChanged(baseAppMaps, isTest(appMapMetadata), this.digests);
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:176]: This is the meat of the fix here - `isNew` and  `isChanged` are only true if `isTest` is also true.

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 3]
```diff
@@ -222,23 +258,91 @@ export default class ChangeReporter {
...
-          failedAppMaps.add(appmap);
-        }
+        if (metadata.test_status === 'failed') failedAppMaps.add(appmap);
       }
     }
     this.failedAppMaps = failedAppMaps;
   }
 }
 
-class ReportGenerator {
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:241]: These functions are new factored out of `ReportGenerator`, so that it's more clear what the data/functional dependencies of each function are.

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 4]
```diff
@@ -222,23 +258,91 @@ export default class ChangeReporter {
...
+  isTestFn: (appmap: AppMapName) => boolean
+): (appmap: AppMapName) => boolean {
+  return (appmap: AppMapName) => isTestFn(appmap) && !baseAppMaps.has(appmap);
+}
+
+// Selects AppMaps that are present in both the base and head revisions, and have different digests.
+export function isChanged(
+  baseAppMaps: Set<AppMapName>,
+  isTestFn: (appmap: AppMapName) => boolean,
+  digests: Digests
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:294]: This is actually a fix also - `isChanged` wasn't checking the digests before. Oops.

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 5]
```diff
@@ -222,23 +258,91 @@ export default class ChangeReporter {
...
+): (appmap: AppMapName) => boolean {
+  return (appmap: AppMapName) =>
+    isTestFn(appmap) &&
+    baseAppMaps.has(appmap) &&
+    digests.appmapDigest(RevisionName.Base, appmap) !==
+      digests.appmapDigest(RevisionName.Head, appmap);
+}
+
+export function buildFailure(
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:303]: This is just a refactor to match the functional style of `isNew` and `isChanged`.

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 6]
```diff
@@ -376,23 +434,23 @@ class ReportGenerator {
...
-    if (this.reporter.reportRemoved) {
+    if (reportRemoved) {
       resolvedFindings = baseFindings.filter((finding) =>
         resolvedFindingHashes.includes(finding.hash_v2)
       );
     } else {
       resolvedFindings = [];
     }
 
-    const result: Record<'new' & 'resolved', Finding[]> = {};
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:387]: This type was wrong; it's properly `'new' | 'resolved'`

File: packages/cli/src/cmds/compare/ChangeReporter.ts [hunk 7]
```diff
@@ -117,36 +122,24 @@ export default class ChangeReporter {
...
     );
 
-    await this.loadMetadata();
-
-    const baseAppMaps = new Set(await this.appmapData.appmaps(RevisionName.Base));
-    const headAppMaps = new Set(await this.appmapData.appmaps(RevisionName.Head));
-    this.newAppMaps = [...headAppMaps].filter((appmap) => !baseAppMaps.has(appmap));
-    this.changedAppMaps = [...headAppMaps]
-      .filter((appmap) => baseAppMaps.has(appmap))
-      .map((appmap) => ({ appmap }));
```
Comment (kgilpin) [inline packages/cli/src/cmds/compare/ChangeReporter.ts:141]: Note that every AppMap that appeared in both `base` and `head` was considered "changed". Ooops. Now an AppMap is only "changed" if it's a test, it appears in both `base` and `head`, and the `digest` has changed.
