### PR TITLE
fix: Empty or invalid Navie responses

### LINKED ISSUE #1601: Server-side messages reported via tokens are not visible to the client through RPC
The socket is closed, and no message is reported to the client.

They see "failed to fetch".

### LINKED ISSUE #1602: No response is returned when search returns zero results
```
Obtained 0 results
```

No tokens are output.

### PR DESCRIPTION
**Pull request by dustinbyrne**
This PR fixes two issues:
1. Responses were not being streamed in if the user had no AppMap matches
2. If the user had not agreed to the latest EULA, the socket would close without notifying the user

Resolves #1601 
Resolves #1602

### CODE REVIEW

File: packages/cli/src/rpc/explain/explain.ts [hunk 1]
```diff
@@ -150,6 +150,20 @@ async function explain(
...
+    explain.on(
+      'complete',
+      () =>
+        first() &&
+        reject(
+          RpcError.fromException(
+            new Error(status.explanation?.join('') || 'The response completed unexpectedly')
+          )
+        )
+    );
```
Comment (dustinbyrne) [inline packages/cli/src/rpc/explain/explain.ts:165]: I could see a case made for this being it's own error message or something similar, though we're not doing anything more with these messages where there's an explicit need to differentiate.

From the servers perspective:
1. A user connects
2. The server determines the user cannot proceed
3. A response is written to the client as raw tokens
4. An `end` message is sent and the connection is terminated

**Review by kgilpin — APPROVED** [review]
