### PR TITLE
fix: scanner works on windows

### LINKED ISSUE #793: AppMap Analysis in VS Code does not produce findings on Windows

### PR DESCRIPTION
**Pull request by ahtrotta**
Fixes #793

### CODE REVIEW

File: packages/scanner/src/cli/scan/watchScan.ts [hunk 1]
```diff
@@ -118,7 +118,8 @@ export class Watcher {
     this.queue.push(mtimePath);
   }
 
-  protected async scan(mtimePath: string): Promise<void> {
+  // eslint-disable-next-line @typescript-eslint/ban-types
+  protected async scan(mtimePath: string, callback?: Function): Promise<void> {
```
Comment (dustinbyrne) [inline packages/scanner/src/cli/scan/watchScan.ts:122]: Good catch. We're compiling down to ES2015 so the native async on this method is replaced with a polyfill. I'm surprised this was only not working on Windows.

My only nit-pick here is the use of `Function` over `() => void | Promise<void>` or a similar typedef. ESLint doesn't like `Function` it because it'll accept any type of function or class.

**Review by dustinbyrne — APPROVED** [review]

File: packages/scanner/src/cli/scan/watchScan.ts (hunk 1 above)
Comment (ahtrotta) [reply packages/scanner/src/cli/scan/watchScan.ts:122]: Okee dokee, I'll change it
