### PR TITLE
fix: OpenAPI accepts either relative or absolute `--appmap-dir` paths

### LINKED ISSUE #860: OpenAPI generation fails when `--appmap-dir` receives an absolute path
```
$ npx @appland/appmap@latest openapi --appmap-dir $(pwd)      
Error: AppMap directory /home/db/dev/applandinc/appmap-server/home/db/dev/applandinc/appmap-server does not exist
    at OpenAPICommand.execute (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/cmds/openapi.js:27:19)
    at Object.handler (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/@appland/appmap/built/cmds/openapi.js:115:35)
    at /home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:8891
    at j (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:9502)
    at M.runCommand (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:7231)
    at Xt.[runYargsParserAndExecuteCommands] (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:57900)
    at Xt.parse (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:40011)
    at Xt.get [as argv] (/home/db/.npm/_npx/93d874c56accaa6c/node_modules/yargs/build/index.cjs:1:61389)
```

### PR DESCRIPTION
**Pull request by dustinbyrne**
Fixes an issue where absolute `--appmap-dir` paths would be appended to the current working directory, leading to an invalid path.

Resolves #860

### CODE REVIEW

File: packages/cli/src/cmds/openapi.ts [hunk 1]
```diff
@@ -58,7 +51,6 @@ class OpenAPICommand {
   }
 
   async collectAppMap(file: string): Promise<void> {
-    this.count += 1;
```
Comment (symwell) [inline packages/cli/src/cmds/openapi.ts:61]: Is this intentional?  Was this a bug? What was the bug?

Comment (dustinbyrne) [reply packages/cli/src/cmds/openapi.ts:61]: As far as I can tell it's not used anywhere, I'm not sure what the purpose is.

**Review by symwell — APPROVED** [review]
